apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_pic_passthru_sriov_netdevice",
                "selectors": {
                    "pciAddresses": ["0000:00:10.0",
                                     "0000:00:10.1",
                                     "0000:00:10.2",
                                     "0000:00:10.3",
                                     "0000:00:11.0",
                                     "0000:00:11.1",
                                     "0000:00:11.2",
                                     "0000:00:11.3"]
                }
            }
        ]
    }
