kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-bird-sdn-vortex-1
  labels:
    k8s-app: nginx-bird-1
spec:
  selector:
    matchLabels:
      k8s-app: nginx-bird-1
  template:
    metadata:
      labels:
        k8s-app: nginx-bird-1
    spec:
      containers:
      - name: nginx	 
        image: registry.gitlab.com/infinitydon/registry/nginx-ubuntu-ip-tools 
      - name: bird-router
        image: registry.gitlab.com/infinitydon/registry/bird:v2.0.7
        command: ["/bin/sh", "-c"]
        args:
        - mkdir -p /etc/bird/;
          cp -rf /bird.conf /etc/bird/;
          SECONDARY_IP=$(ip add show dev net1 | grep -Po 'inet \K[\d.]+');
          sed -i "s/{{ NODE_IP }}/${SECONDARY_IP}/g" /etc/bird/bird.conf;
          ip link add dummy1 type dummy;
          ip addr add 192.168.200.200/32 dev dummy1;
          ip link set dev dummy1 up;
          echo 200 k8s >> /etc/iproute2/rt_tables;
          ip rule add from ${SECONDARY_IP} k8s;
          ip rule add from 192.168.200.200 table k8s;
          ip route add default via 172.18.0.1 table k8s;
          bird -c /etc/bird/bird.conf -d
        volumeMounts:
        - mountPath: /bird.conf
          name: bird-config
          subPath: "bird.conf"		  
        securityContext:
             privileged: true
      initContainers:
      - name: init-network-client
        image: sdnvortex/network-controller:v0.4.9
        command: ["/go/bin/client"]
        args: ["-s=unix:///tmp/vortex.sock", "-b=br0", "-n=net1", "-i=172.18.0.2/24"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex/
      - name: tun-volume
        hostPath:
          path: /dev/net/tun
      - name: bird-config
        configMap:
          name: bird-ospf-configuration
