apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-def-1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "enp0s9",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "subnet": "172.18.0.0/24",
        "rangeStart": "172.18.0.2",
        "rangeEnd": "172.18.0.50",
        "gateway": "172.18.0.1"
      }
    }'
