apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-def-1-srb-wab
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins":
       [
        {
       "type": "ipvlan",
       "master": "enp0s9",
       "mode": "l2",
       "ipam": {
        "type": "whereabouts",
        "range": "172.30.0.0/24",
        "range_start": "172.30.0.2",
        "range_end": "172.30.0.50",
        "gateway": "172.30.0.1"
          }
       },
       { "type": "sbr" }
       ]
    }'
