apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-def-1-srb-wab
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins":
       [
        {
       "type": "ipvlan",
       "master": "enp0s9",
       "mode": "l2",
       "ipam": {
        "type": "whereabouts",
        "subnet": "172.18.0.0/24",
        "exclude": [ "172.18.0.1" ]
          }
       },
           { "type": "sbr" }
       ]
    }'
